- name: Build and Deploy Petstore
  hosts: local
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "majithas"
        password: "dckr_pat_vw2vZK9Gr5u0eFmwdZ0Sog32dvU"

    - name: Build and Push Docker image
      community.docker.docker_image:
        name: "majithas/petstore"
        tag: latest
        build:
          path: /var/lib/jenkins/workspace/petstore
        push: yes
        source: build

    - name: Run Petstore container
      community.docker.docker_container:
        name: pet1
        image: "majithas/petstore:latest"
        state: started
        restart_policy: always
        published_ports:
          - "8081:8080"
